### ISSUE TITLE
Dry leaves and sticks on the ground of Level 10 are rotated

### ISSUE THREAD

**Issue by orazioedoardo** [jorio/Bugdom2#3]
In the beehive area, leaves and sticks are rotated compared to an [old footage](https://www.youtube.com/watch?v=KqaAyKdvGAg). Location appears correct. I don't know if it is due to a slightly different version or an indication of some small bug in the code. Weirdly, one stick and one leaf lay (unreachable obviously) on top of the tree.

**Comment by jorio** [comment]
Kindling is given a random rotation: https://github.com/jorio/Bugdom2/blob/6ff4b3474c561a7fb054da159f4e28d5e8775178/Source/Items/BeeHive.c#L250

> one stick and one leaf lay (unreachable obviously) on top of the tree

I assume those were originally placed on the ground, and the tree trunk's collision box was probably enlarged later.
![Screenshot_20231010_193947](https://github.com/jorio/Bugdom2/assets/837086/3e294149-47e8-4fc5-b1c5-8efc75ebe957)

**Comment by orazioedoardo** [comment]
> Kindling is given a random rotation:

Oh, didn't see that.

**Comment by jorio** [comment]
Good catch though - I would never have noticed those if you hadn't pointed them out ;)
