### ISSUE TITLE
Write a meaningful summary

### ISSUE THREAD

**Issue by razzeee** [jorio/Bugdom2#5]
Hey there,

the summary https://github.com/jorio/Bugdom2/blob/master/packaging/io.jor.bugdom2.appdata.xml#L7 shouldn't mirror the app title and be something more like a tag line.

There are additional guidelines at https://docs.flathub.org/docs/for-app-authors/appdata-guidelines/quality-guidelines/#summary

**Comment by jorio** [comment]
Oops, that was an oversight. I'll update the flatpak soon. Thanks!
